server:
  port: 8081

### Spring Properties
spring:
  graphql:
    graphiql:
      enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  # PRES SQL Server datasource Properties
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-graphql
    username: root
    password: Test@2020
    driver-class-name: com.mysql.cj.jdbc.Driver


  # JPA properties
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        ddl-auto: update
        show_sql: false

  # Logging
logging:
  level:
    org:
      springframework:
        web: DEBUG

